services:
  db:
    image: postgres:17.3-alpine
    container_name: project_name-db
    command: postgres -c 'max_connections=250'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: project_name
      POSTGRES_USER: project_name
      POSTGRES_DB: project_name
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5332:5432

volumes:
  postgres:
    name: project_name-db
    driver: local