services:
  db:
    image: mariadb:11.7.2
    container_name: project_name_db
    ports:
      - 3409:3306
    volumes:
      - mariadb_origin:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=project_name
      - MYSQL_USER=project_name
      - MYSQL_PASSWORD=project_name
      - MYSQL_ROOT_PASSWORD=project_name

  phpmyadmin:
    image: phpmyadmin
    container_name: project_name_phpmyadmin
    ports:
      - 8409:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=project_name
      - PMA_PASSWORD=project_name

volumes:
  mariadb_origin:
    name: project_name_db
