ktor:
  application:
    modules:
      - com.company.ApplicationKt.module
  deployment:
    port: 7056

db:
#  url: "jdbc:mariadb://localhost:3409/project_name"
  url: "jdbc:postgresql://localhost:5332/project_name"
  user: project_name
  password: project_name

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

kafka:
  bootstrapServers: [ "localhost:9092" ]
  groupId: "group1"
  consumers:
    cons1:
      topic: "topic1"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      autoOffsetReset: "earliest"
  producers:
    stringProducer:
      topic: "topic1"
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "org.apache.kafka.common.serialization.StringSerializer"
      acks: all
    intProducer:
      topic: "topic1"
      keySerializer: "org.apache.kafka.common.serialization.IntegerSerializer"
      valueSerializer: "org.apache.kafka.common.serialization.StringSerializer"
